package Vista.Recargas;

import Controlador.CLlave;
import Modelo.MTuLlave;
import java.sql.Date;
import java.text.ParseException;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Steve
 */
public class TuLlave extends javax.swing.JFrame {

    /**
     * Creates new form TuLlave
     */
    public TuLlave() {
        initComponents();
        btnIngresar.setEnabled(false);
        btnRecargar.setEnabled(false);
        try {
            Date sqlDate = new Date(txtFecha.getDateFormat().parse(txtFecha.getText()).getTime());
            MTuLlave recarga = new CLlave().Consultar(sqlDate);
            recarga.calcular();
            txtRecargas.setText(recarga.getRecargas()+"");
            txtVentas.setText(recarga.getVentas()+"");
            txtSaldo.setText(recarga.getSaldo()+"");
            txtCaja.setText(recarga.getCaja()+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error: "+e);
        }
    }
    public void limpiar(){
        txtRecargas.setText(0+"");
        txtVentas.setText(0+"");
        txtSaldo.setText(0+"");
        txtCaja.setText(0+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRecargas = new javax.swing.JTextField();
        txtVentas = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtCaja = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        txtRecargar = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        txtFecha = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tu Llave");

        jLabel1.setText("Fecha");

        jLabel2.setText("Recargas");

        jLabel3.setText("Ventas");

        jLabel4.setText("Saldo");

        jLabel5.setText("Plata en caja");

        txtRecargas.setEditable(false);
        txtRecargas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRecargasFocusLost(evt);
            }
        });

        txtVentas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVentasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVentasFocusLost(evt);
            }
        });

        txtSaldo.setEditable(false);
        txtSaldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSaldoFocusLost(evt);
            }
        });

        txtCaja.setEditable(false);
        txtCaja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCajaFocusLost(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultas");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        txtRecargar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRecargarFocusLost(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtFecha.setFormat(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecargas)
                            .addComponent(txtVentas)
                            .addComponent(txtSaldo)
                            .addComponent(txtCaja)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtRecargar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresar)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addComponent(btnRecargar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRecargas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnConsultar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecargar)
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        try {
            Date sqlDate = new Date(txtFecha.getDateFormat().parse(txtFecha.getText()).getTime());
            boolean reca = new MTuLlave().recargar(sqlDate, Long.parseLong(txtRecargar.getText()));
            String mensaje = reca?"Saldo agregado":"Algo sucedio, por favor revise los datos de las tablas soluciones y tu llave o revisé sí la transacción se realizó";
            JOptionPane.showMessageDialog(this,mensaje);
            txtRecargar.setText(null);
            btnRecargar.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(TuRed.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {
            MTuLlave recarga = new MTuLlave();
            Date sqlDate = new Date(txtFecha.getDateFormat().parse(txtFecha.getText()).getTime());
            recarga.setFecha(sqlDate);
            recarga.setRecargas(Long.parseLong(txtRecargas.getText()));
            recarga.setVentas(Long.parseLong(txtVentas.getText()));
            recarga.setSaldo(Long.parseLong(txtSaldo.getText()));
            recarga.setCaja(Long.parseLong(txtCaja.getText()));
            recarga.calcular();
            boolean reca = new CLlave().Insertar(recarga);
            String mensaje = reca?"Tu Llave Registrado":"Tu Llave NO Registrado";
            limpiar();
            JOptionPane.showMessageDialog(this,mensaje);
            btnIngresar.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(TuRed.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            Date sqlDate = new Date(txtFecha.getDateFormat().parse(txtFecha.getText()).getTime());
            boolean reca = new CLlave().Eliminar(sqlDate);
            String mensaje = reca?"Tu Llave Registrado":"Tu Llave NO Registrado";
            JOptionPane.showMessageDialog(this,mensaje);
        } catch (ParseException ex) {
            Logger.getLogger(TuRed.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(btnActualizar.getText().equals("Actualizar")){
            try {
                btnActualizar.setText("Cargar");
                btnEliminar.setEnabled(false);
                btnConsultar.setEnabled(false);
                Date sqlDate = new Date(txtFecha.getDateFormat().parse(txtFecha.getText()).getTime());
                MTuLlave recarga = new CLlave().Consultar(sqlDate);
                recarga.calcular();
                txtRecargas.setText(recarga.getRecargas()+"");
                txtVentas.setText(recarga.getVentas()+"");
                txtSaldo.setText(recarga.getSaldo()+"");
                txtCaja.setText(recarga.getCaja()+"");
            } catch (ParseException ex) {
                Logger.getLogger(TuRed.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                btnActualizar.setText("Actualizar");
                btnEliminar.setEnabled(true);
                btnConsultar.setEnabled(true);
                MTuLlave recarga = new MTuLlave();
                Date sqlDate = new Date(txtFecha.getDateFormat().parse(txtFecha.getText()).getTime());
                recarga.setFecha(sqlDate);
                recarga.setRecargas(Long.parseLong(txtRecargas.getText()));
                recarga.setVentas(Long.parseLong(txtVentas.getText()));
                recarga.setSaldo(Long.parseLong(txtSaldo.getText()));
                recarga.setCaja(Long.parseLong(txtCaja.getText()));
                recarga.calcular();
                boolean reca = new CLlave().Actualizar(recarga);
                Date actual = new Date(Calendar.getInstance().getTime().getTime());
                List<MTuLlave> todos = new CLlave().ConsultarRango(recarga.getFecha(), actual);
                int i=0;
                while(i<todos.size()){
                    if(i==0){
                        todos.get(i).calcular();
                    }
                    else{
                        todos.get(i).calcular(todos.get(i-1));
                    }
                    i++;
                }
                boolean reca2 = new CLlave().Actualizar(todos);
                reca = reca||reca2;
                String mensaje = reca?"Tu Llave Registrado":"Tu Llave NO Registrado";
                limpiar();
                JOptionPane.showMessageDialog(this,mensaje);
            } catch (ParseException ex) {
                Logger.getLogger(TuRed.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtRecargasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRecargasFocusLost
        boolean reca = txtRecargas.getText().isEmpty()||txtVentas.getText().isEmpty()||txtSaldo.getText().isEmpty()||txtCaja.getText().isEmpty();
        btnIngresar.setEnabled(!reca);
    }//GEN-LAST:event_txtRecargasFocusLost

    private void txtVentasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVentasFocusLost
        boolean reca = txtRecargas.getText().isEmpty()||txtVentas.getText().isEmpty()||txtSaldo.getText().isEmpty()||txtCaja.getText().isEmpty();
        btnIngresar.setEnabled(!reca);
    }//GEN-LAST:event_txtVentasFocusLost

    private void txtSaldoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaldoFocusLost
        boolean reca = txtRecargas.getText().isEmpty()||txtVentas.getText().isEmpty()||txtSaldo.getText().isEmpty()||txtCaja.getText().isEmpty();
        btnIngresar.setEnabled(!reca);
    }//GEN-LAST:event_txtSaldoFocusLost

    private void txtCajaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCajaFocusLost
        boolean reca = txtRecargas.getText().isEmpty()||txtVentas.getText().isEmpty()||txtSaldo.getText().isEmpty()||txtCaja.getText().isEmpty();
        btnIngresar.setEnabled(!reca);
    }//GEN-LAST:event_txtCajaFocusLost

    private void txtVentasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVentasFocusGained

    }//GEN-LAST:event_txtVentasFocusGained

    private void txtRecargarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRecargarFocusLost
        btnRecargar.setEnabled(!txtRecargar.getText().isEmpty());
    }//GEN-LAST:event_txtRecargarFocusLost

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Consultar objConsulta = new Consultar();
        objConsulta.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TuLlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TuLlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TuLlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TuLlave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TuLlave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCaja;
    private datechooser.beans.DateChooserCombo txtFecha;
    private javax.swing.JTextField txtRecargar;
    private javax.swing.JTextField txtRecargas;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtVentas;
    // End of variables declaration//GEN-END:variables
}
